!     -*- f90 -*-
!     This file is autogenerated with f2py (version:1.24.3)
!     It contains Fortran 90 wrappers to fortran functions.

      
      subroutine f2pyinitahestetic(f2pysetupfunc)
      use ahestetic, only : dash1_line
      use ahestetic, only : dash2_line
      use ahestetic, only : dash3_line
      use ahestetic, only : hash1_line
      use ahestetic, only : hash2_line
      use ahestetic, only : hash3_line
      use ahestetic, only : prog1_line
      use ahestetic, only : prog2_line
      external f2pysetupfunc
      call f2pysetupfunc(dash1_line,dash2_line,dash3_line,hash1_line,has&
     &h2_line,hash3_line,prog1_line,prog2_line)
      end subroutine f2pyinitahestetic


